### ISSUE TITLE
Incorrect code is generated for oneOf schema

### ISSUE THREAD

**Issue by Dema** [ajaishankar/openapi-typescript-fetch#16]
`'AbstractRequestStepDto' is referenced directly or indirectly in its own type annotation.`

[swagger-challenge-service.json.gz](https://github.com/ajaishankar/openapi-typescript-fetch/files/8304562/swagger-challenge-service.json.gz)

**Comment by ajaishankar** [comment]
Hi @Dema for problems with codegen could you raise the issue in [openapi-typescript](https://github.com/drwpow/openapi-typescript) project? 

This repo is just the fetch implementation...
