### ISSUE TITLE
Generate error request when request body is an array.

### ISSUE THREAD

**Issue by XMLHexagram** [ajaishankar/openapi-typescript-fetch#17]
Because [`const payload = { ...request.payload }`](https://github.com/ajaishankar/openapi-typescript-fetch/blob/main/src/fetcher.ts#L112) in fetcher.ts.
If I try to use something like `[{count:1},{count:2}]` the really request will become
 ```json
{
  '0': { count: 1 },
  '1': { count: 1 }
} 
```

**Comment by XMLHexagram** [comment]
I think this is a bug and I will try to fix it.

**Comment by laosb** [comment]
Technically, other primitive JSON values like `"string"` or `42` can also be placed at top level. Not sure whether OpenAPI spec allows that. If so, maybe needs to consider them.

**Comment by ajaishankar** [comment]
Array as a parameter is something that would be pretty common, thanks @XMLHexagram for the fix...

**Comment by flip-it** [comment]
When can this fix be released @ajaishankar?

**Comment by ajaishankar** [comment]
@flip-it this fix is available in the latest release 1.1.3. Also added a utility method to deal with arrays [here](https://github.com/ajaishankar/openapi-typescript-fetch#utility-methods)
