### ISSUE TITLE
Typing fetch errors

### ISSUE THREAD

**Issue by sebas-intellegens** [ajaishankar/openapi-typescript-fetch#2]
First of all thanks for this library, it's really useful 👍 

I'm not sure how it is suppose to work but I'm assuming to get a type on `error` in the `.catch(error => {})` callback one should do something like this `if (error instanceof ApiError)`? Is that right?

Additionally, would it be possible to take into account the defined return type for certain HTTP error statuses from `schema.ts`? 
Like these: https://github.com/drwpow/openapi-typescript/blob/main/tests/v3/expected/petstore.ts#L423-L426
Here it is `unknown` but it is possible to return a custom JSON object on 400 as well.
Would be really nice to have that type on `error.data`. Not sure yet how it could be typed conditional on the status code defined in the OA spec.

(I'm dealing with OpenAPI 3.0 in my case)

**Comment by ajaishankar** [comment]
@sebas-intellegens have added [typed error handling](https://github.com/ajaishankar/openapi-typescript-fetch/#typed-error-handling) support. Do try on your schema, feedback welcome 🙏

**Comment by sebas-intellegens** [comment]
> @sebas-intellegens have added [typed error handling](https://github.com/ajaishankar/openapi-typescript-fetch/#typed-error-handling) support. Do try on your schema, feedback welcome pray

Thanks @ajaishankar. Just tried it out, works as expected :+1:
