### ISSUE TITLE
Running in Jest tests React-Testing-Library?

### ISSUE THREAD

**Issue by mattdemichele-pearson** [ajaishankar/openapi-typescript-fetch#26]
Has anybody got this to successfully work in a jest test with RTL or anything else for unit tests? I tried using the node-fetch polyfill, but I cannot seem to get it to work. Maybe I am doing something wrong? Was wondering if anybody else has figured it out and had any tips?

**Comment by ajaishankar** [comment]
It should work fine with jest `testEnvironment: "jsdom"` without needing any polyfill...

For example a new create-react-app

```
npx create-react-app test-fetch --template typescript
cd test-fetch
npm install openapi-typescript-fetch
cd src
npx openapi-typescript https://petstore.swagger.io/v2/swagger.json --output petstore.ts
```
Replace [src/App.test.tsx](https://gist.github.com/ajaishankar/39e1b58c9b0917d814bfa9383236186f)

```
npm test
```

**Comment by mattdemichele-pearson** [comment]
As far as I understand, create-react-app does a polyfill behind the scenes with whatwg-fetch.

https://github.com/facebook/create-react-app/blob/63bba07d584a769cfaf7699e0aab92ed99c3c57e/packages/react-scripts/scripts/utils/createJestConfig.js#L32

https://github.com/facebook/create-react-app/blob/bb64e31a81eb12d688c14713dce812143688750a/packages/react-app-polyfill/README.md

But it is good to know that you have gotten it working under a basic scenario, so it must be something wrong with my setup. Thanks for the help!

**Comment by ajaishankar** [comment]
NodeJS usage with node-fetch is also documented here:

https://github.com/ajaishankar/openapi-typescript-fetch#server-side-usage

Hope it helps...
