### ISSUE TITLE
Invalid Typescript schema requested for POST

### ISSUE THREAD

**Issue by bnhovde** [ajaishankar/openapi-typescript-fetch#3]
Hi, love this initiative. It's allowed me to remove hundreds of lines of code.

I've got a strange problem trying to wire up a POST request using the standard approach:

`export const submitForm = fetcher.path('/form/{formId}/submit').method('post').create();`

The Swagger API definition requests `formId` as a parameter and formFields as the post body, but the returned function requests the following input, a intersection between an object and an array, which is impossible to provide:

![image](https://user-images.githubusercontent.com/4840600/139056788-21bda6f7-bb71-46cd-a867-160f31c005b8.png)

I might be doing something wrong, but it seems like a potential bug. Here's the type for the request:

```
"/form/{formId}/submit": {
    post: {
      parameters: {
        path: {
          formId: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FormModel"];
            "application/json": components["schemas"]["FormModel"];
            "text/json": components["schemas"]["FormModel"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json":
            | components["schemas"]["FormFieldInputModel"][]
            | null;
          "text/json": components["schemas"]["FormFieldInputModel"][] | null;
          "application/*+json":
            | components["schemas"]["FormFieldInputModel"][]
            | null;
        };
      };
    };
  };


```

**Comment by kirypto** [comment]
Hate to say it, but I think I might have evidence that top level arrays in a body is a fairly common usecase: [RFC 6902 - Section 3](https://www.rfc-editor.org/rfc/rfc6902#section-3).

That being said, it does look like the workaround and the utility function `arrayRequestBody` you provided is doing the trick! Just made use of it, and as with the rest of the library, it trivialized the problem. Really glad I ran across this library.
Honestly this is the first time I've had an API service actually backed directly by the openapi spec with type validation and it's fantastic.
