### ISSUE TITLE
Query params are required as params of create method

### ISSUE THREAD

**Issue by JanCizmar** [ajaishankar/openapi-typescript-fetch#30]
For some reason it requires to provide the query params in object provided to create method, but it accepts only values "true" or 1.

**Comment by ajaishankar** [comment]
@JanCizmar see issue and reason here https://github.com/ajaishankar/openapi-typescript-fetch/issues/28#issuecomment-1124881585

**Comment by JanCizmar** [comment]
Then I would recommend to specify it in docs. But I still don't know, why the library needs to know it in the create method before calling the actual fetch?
