### ISSUE TITLE
Remove coalescing of OpErrorType with unknown.

### ISSUE THREAD

**Issue by aidan-keay** [ajaishankar/openapi-typescript-fetch#4]
Firstly, thank you for creating this library, it's fantastic.

The code in question:

```ts
export type OpErrorType<OP> = Coalesce<
  _OpErrorType<OpResponseTypes<OP>>,
  unknown
>
```

If there are no error types defined for an operation, OpErrorType is coalesced to unknown. I think this should remain as never because the error type _is_ known, it's just empty. In our codebase we end up taking the union of FetchErrorType<typeof fetchFunction> with ApiError to create a union type of all known error types an operation can throw. If FetchErrorType is unknown, the resulting union is unknown instead of just ApiError, which is not desirable in our case.

```ts
type Undesirable = unknown | ApiError; // unknown
type Desirable = never | ApiError; // ApiError
```

**Comment by ajaishankar** [comment]
@aidan-keay thanks for the feedback!

I think instead of never it'll be better to coalesce to `ApiError` since that is the default error type.

```ts
export type OpErrorType<OP> = Coalesce<
  _OpErrorType<OpResponseTypes<OP>>,
  ApiError
>
```
Will push the change later today...

**Comment by aidan-keay** [comment]
> @aidan-keay thanks for the feedback!
> 
> I think instead of never it'll be better to coalesce to `ApiError` since that is the default error type.
> 
> ```ts
> export type OpErrorType<OP> = Coalesce<
>   _OpErrorType<OpResponseTypes<OP>>,
>   ApiError
> >
> ```
> 
> Will push the change later today...

Ok, that sounds good, thank you!

**Comment by aidan-keay** [comment]
@ajaishankar I noticed that when coalescing with ApiError, ApiError is not included in the resulting union type. Do you think it may be better to use a union here?

**Comment by ajaishankar** [comment]
@aidan-keay publised new version that coalesces default error type to `{ status: number; data: any }` (https://github.com/ajaishankar/openapi-typescript-fetch/commit/7b92d74f26d786500d12d8e5dd0905d38917e050)

**Comment by aidan-keay** [comment]
> @aidan-keay publised new version that coalesces default error type to `{ status: number; data: any }` ([7b92d74](https://github.com/ajaishankar/openapi-typescript-fetch/commit/7b92d74f26d786500d12d8e5dd0905d38917e050))

Ok, thank you. :)
