### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by aidan-keay** [ajaishankar/openapi-typescript-fetch#6]
Thanks again for creating this incredibly useful library. I would love to incorporate it into a project I am working on although I wanted to check the licensing terms. I noticed that the `package.json` says a license type is `ISC` although there wasn't a separate license file in the repo. Just to clarify, are others free to use this software in their own projects (i.e. MIT / ISC license)?

Kind regards,
Aidan

**Comment by ajaishankar** [comment]
Thanks @aidan-keay 

Have updated the license to MIT and added license file. Yes, others are free to use this software in their projects 👍
